spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/development
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update